# Generated by Django 6.0.6 on 2026-06-18 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120, verbose_name='Nama lengkap')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Posisi yang dicari')),
                ('skills', models.CharField(blank=True, max_length=500, verbose_name='Skills / kemampuan')),
                ('experience', models.CharField(blank=True, max_length=500, verbose_name='Pengalaman / deskripsi')),
                ('education', models.CharField(blank=True, max_length=100, verbose_name='Pendidikan')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Lokasi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
